/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.mavenproject2;

import java.util.HashSet;

/**
 *
 * @author João
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        TituloPagina = new javax.swing.JLabel();
        PainelBotaoVoltar = new javax.swing.JPanel();
        BotaoVoltar = new javax.swing.JButton();
        PainelColaborador1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        HoraExtra1 = new javax.swing.JTextField();
        HoraExtraNot1 = new javax.swing.JTextField();
        HoraExtraFeriado1 = new javax.swing.JTextField();
        TotalHoraExtra1 = new javax.swing.JTextField();
        Colaborador1 = new javax.swing.JTextField();
        PainelColaborador2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        HoraExtra2 = new javax.swing.JTextField();
        HoraExtraNot2 = new javax.swing.JTextField();
        HoraExtraFeriado2 = new javax.swing.JTextField();
        TotalHoraExtra2 = new javax.swing.JTextField();
        Colaborador2 = new javax.swing.JTextField();
        PainelColaborador3 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        HoraExtra3 = new javax.swing.JTextField();
        HoraExtraNot3 = new javax.swing.JTextField();
        HoraExtraFeriado3 = new javax.swing.JTextField();
        TotalHoraExtra3 = new javax.swing.JTextField();
        Colaborador3 = new javax.swing.JTextField();
        PainelColaborador4 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        HoraExtra4 = new javax.swing.JTextField();
        HoraExtraNot4 = new javax.swing.JTextField();
        HoraExtraFeriado4 = new javax.swing.JTextField();
        TotalHoraExtra4 = new javax.swing.JTextField();
        Colaborador4 = new javax.swing.JTextField();
        PainelColaborador5 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        HoraExtra5 = new javax.swing.JTextField();
        HoraExtraNot5 = new javax.swing.JTextField();
        HoraExtraFeriado5 = new javax.swing.JTextField();
        TotalHoraExtra5 = new javax.swing.JTextField();
        Colaborador5 = new javax.swing.JTextField();
        PainelBotoesInferiores = new javax.swing.JPanel();
        BotaoEditar = new javax.swing.JButton();
        BotaoConfirmar = new javax.swing.JButton();
        BotaoCancelar = new javax.swing.JButton();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculo hora extra");
        setBackground(new java.awt.Color(227, 235, 238));
        setForeground(new java.awt.Color(227, 235, 238));

        TituloPagina.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        TituloPagina.setText("Cálculo hora extra");

        PainelBotaoVoltar.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N

        BotaoVoltar.setBackground(new java.awt.Color(94, 119, 255));
        BotaoVoltar.setText("Voltar");
        BotaoVoltar.setBorderPainted(false);
        BotaoVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PainelBotaoVoltarLayout = new javax.swing.GroupLayout(PainelBotaoVoltar);
        PainelBotaoVoltar.setLayout(PainelBotaoVoltarLayout);
        PainelBotaoVoltarLayout.setHorizontalGroup(
                PainelBotaoVoltarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(PainelBotaoVoltarLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(BotaoVoltar)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PainelBotaoVoltarLayout.setVerticalGroup(
                PainelBotaoVoltarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(PainelBotaoVoltarLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(BotaoVoltar)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PainelColaborador1.setBackground(new java.awt.Color(227, 235, 238));

        jLabel2.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel2.setText("H extra");

        jLabel3.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel3.setText("Colaborador");

        jLabel4.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel4.setText("H extra noturna");

        jLabel5.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel5.setText("H extra feriado");

        jLabel6.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel6.setText("Total");

        HoraExtra1.setEditable(false);
        HoraExtra1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HoraExtra1ActionPerformed(evt);
            }
        });

        HoraExtraNot1.setEditable(false);
        HoraExtraNot1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HoraExtraNot1ActionPerformed(evt);
            }
        });

        HoraExtraFeriado1.setEditable(false);

        TotalHoraExtra1.setEditable(false);

        Colaborador1.setEditable(false);
        Colaborador1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Colaborador1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PainelColaborador1Layout = new javax.swing.GroupLayout(PainelColaborador1);
        PainelColaborador1.setLayout(PainelColaborador1Layout);
        PainelColaborador1Layout.setHorizontalGroup(
                PainelColaborador1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(PainelColaborador1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(PainelColaborador1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3)
                                        .addGroup(PainelColaborador1Layout.createSequentialGroup()
                                                .addGap(6, 6, 6)
                                                .addComponent(Colaborador1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(23, 23, 23)
                                .addGroup(PainelColaborador1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(PainelColaborador1Layout.createSequentialGroup()
                                                .addGap(19, 19, 19)
                                                .addComponent(HoraExtra1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(26, 26, 26)
                                                .addComponent(HoraExtraNot1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelColaborador1Layout.createSequentialGroup()
                                                .addComponent(jLabel2)
                                                .addGap(71, 71, 71)
                                                .addComponent(jLabel4)
                                                .addGap(13, 13, 13)))
                                .addGroup(PainelColaborador1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(PainelColaborador1Layout.createSequentialGroup()
                                                .addGap(38, 38, 38)
                                                .addComponent(jLabel5)
                                                .addGap(78, 78, 78)
                                                .addComponent(jLabel6)
                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(PainelColaborador1Layout.createSequentialGroup()
                                                .addGap(26, 26, 26)
                                                .addComponent(HoraExtraFeriado1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(28, 28, 28)
                                                .addComponent(TotalHoraExtra1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 20, Short.MAX_VALUE))))
        );
        PainelColaborador1Layout.setVerticalGroup(
                PainelColaborador1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelColaborador1Layout.createSequentialGroup()
                                .addGroup(PainelColaborador1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(PainelColaborador1Layout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addGroup(PainelColaborador1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel3)
                                                        .addComponent(jLabel4)))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelColaborador1Layout.createSequentialGroup()
                                                .addContainerGap(18, Short.MAX_VALUE)
                                                .addGroup(PainelColaborador1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelColaborador1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                .addComponent(jLabel5)
                                                                .addComponent(jLabel6))
                                                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))))
                                .addGroup(PainelColaborador1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(PainelColaborador1Layout.createSequentialGroup()
                                                .addGap(6, 6, 6)
                                                .addGroup(PainelColaborador1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(HoraExtraFeriado1)
                                                        .addGroup(PainelColaborador1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                .addComponent(HoraExtraNot1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(HoraExtra1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addComponent(Colaborador1)))
                                        .addGroup(PainelColaborador1Layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(TotalHoraExtra1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap())
        );

        PainelColaborador2.setBackground(new java.awt.Color(227, 235, 238));

        jLabel7.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel7.setText("H extra");

        jLabel8.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel8.setText("Colaborador");

        jLabel9.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel9.setText("H extra noturna");

        jLabel10.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel10.setText("H extra feriado");

        jLabel11.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel11.setText("Total");

        HoraExtra2.setEditable(false);
        HoraExtra2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HoraExtra2ActionPerformed(evt);
            }
        });

        HoraExtraNot2.setEditable(false);
        HoraExtraNot2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HoraExtraNot2ActionPerformed(evt);
            }
        });

        HoraExtraFeriado2.setEditable(false);

        TotalHoraExtra2.setEditable(false);

        Colaborador2.setEditable(false);
        Colaborador2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Colaborador2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PainelColaborador2Layout = new javax.swing.GroupLayout(PainelColaborador2);
        PainelColaborador2.setLayout(PainelColaborador2Layout);
        PainelColaborador2Layout.setHorizontalGroup(
                PainelColaborador2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(PainelColaborador2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(PainelColaborador2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel8)
                                        .addGroup(PainelColaborador2Layout.createSequentialGroup()
                                                .addGap(6, 6, 6)
                                                .addComponent(Colaborador2, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(23, 23, 23)
                                .addGroup(PainelColaborador2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(PainelColaborador2Layout.createSequentialGroup()
                                                .addGap(19, 19, 19)
                                                .addComponent(HoraExtra2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(26, 26, 26)
                                                .addComponent(HoraExtraNot2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelColaborador2Layout.createSequentialGroup()
                                                .addComponent(jLabel7)
                                                .addGap(71, 71, 71)
                                                .addComponent(jLabel9)
                                                .addGap(13, 13, 13)))
                                .addGroup(PainelColaborador2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(PainelColaborador2Layout.createSequentialGroup()
                                                .addGap(38, 38, 38)
                                                .addComponent(jLabel10)
                                                .addGap(78, 78, 78)
                                                .addComponent(jLabel11)
                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(PainelColaborador2Layout.createSequentialGroup()
                                                .addGap(26, 26, 26)
                                                .addComponent(HoraExtraFeriado2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(28, 28, 28)
                                                .addComponent(TotalHoraExtra2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 20, Short.MAX_VALUE))))
        );
        PainelColaborador2Layout.setVerticalGroup(
                PainelColaborador2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelColaborador2Layout.createSequentialGroup()
                                .addGroup(PainelColaborador2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(PainelColaborador2Layout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addGroup(PainelColaborador2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel8)
                                                        .addComponent(jLabel9)))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelColaborador2Layout.createSequentialGroup()
                                                .addContainerGap(18, Short.MAX_VALUE)
                                                .addGroup(PainelColaborador2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelColaborador2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                .addComponent(jLabel10)
                                                                .addComponent(jLabel11))
                                                        .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING))))
                                .addGroup(PainelColaborador2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(PainelColaborador2Layout.createSequentialGroup()
                                                .addGap(6, 6, 6)
                                                .addGroup(PainelColaborador2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(HoraExtraFeriado2)
                                                        .addGroup(PainelColaborador2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                .addComponent(HoraExtraNot2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(HoraExtra2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addComponent(Colaborador2)))
                                        .addGroup(PainelColaborador2Layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(TotalHoraExtra2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap())
        );

        PainelColaborador3.setBackground(new java.awt.Color(227, 235, 238));

        jLabel12.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel12.setText("H extra");

        jLabel13.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel13.setText("Colaborador");

        jLabel14.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel14.setText("H extra noturna");

        jLabel15.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel15.setText("H extra feriado");

        jLabel16.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel16.setText("Total");

        HoraExtra3.setEditable(false);
        HoraExtra3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HoraExtra3ActionPerformed(evt);
            }
        });

        HoraExtraNot3.setEditable(false);
        HoraExtraNot3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HoraExtraNot3ActionPerformed(evt);
            }
        });

        HoraExtraFeriado3.setEditable(false);

        TotalHoraExtra3.setEditable(false);

        Colaborador3.setEditable(false);
        Colaborador3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Colaborador3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PainelColaborador3Layout = new javax.swing.GroupLayout(PainelColaborador3);
        PainelColaborador3.setLayout(PainelColaborador3Layout);
        PainelColaborador3Layout.setHorizontalGroup(
                PainelColaborador3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(PainelColaborador3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(PainelColaborador3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel13)
                                        .addGroup(PainelColaborador3Layout.createSequentialGroup()
                                                .addGap(6, 6, 6)
                                                .addComponent(Colaborador3, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(23, 23, 23)
                                .addGroup(PainelColaborador3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(PainelColaborador3Layout.createSequentialGroup()
                                                .addGap(19, 19, 19)
                                                .addComponent(HoraExtra3, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(26, 26, 26)
                                                .addComponent(HoraExtraNot3, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelColaborador3Layout.createSequentialGroup()
                                                .addComponent(jLabel12)
                                                .addGap(73, 73, 73)
                                                .addComponent(jLabel14)
                                                .addGap(13, 13, 13)))
                                .addGroup(PainelColaborador3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(PainelColaborador3Layout.createSequentialGroup()
                                                .addGap(38, 38, 38)
                                                .addComponent(jLabel15)
                                                .addGap(78, 78, 78)
                                                .addComponent(jLabel16)
                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(PainelColaborador3Layout.createSequentialGroup()
                                                .addGap(26, 26, 26)
                                                .addComponent(HoraExtraFeriado3, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(28, 28, 28)
                                                .addComponent(TotalHoraExtra3, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 20, Short.MAX_VALUE))))
        );
        PainelColaborador3Layout.setVerticalGroup(
                PainelColaborador3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelColaborador3Layout.createSequentialGroup()
                                .addGroup(PainelColaborador3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(PainelColaborador3Layout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addGroup(PainelColaborador3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel13)
                                                        .addComponent(jLabel14)))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelColaborador3Layout.createSequentialGroup()
                                                .addContainerGap(18, Short.MAX_VALUE)
                                                .addGroup(PainelColaborador3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelColaborador3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                .addComponent(jLabel15)
                                                                .addComponent(jLabel16))
                                                        .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING))))
                                .addGroup(PainelColaborador3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(PainelColaborador3Layout.createSequentialGroup()
                                                .addGap(6, 6, 6)
                                                .addGroup(PainelColaborador3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(HoraExtraFeriado3)
                                                        .addGroup(PainelColaborador3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                .addComponent(HoraExtraNot3, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(HoraExtra3, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addComponent(Colaborador3)))
                                        .addGroup(PainelColaborador3Layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(TotalHoraExtra3, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap())
        );

        PainelColaborador4.setBackground(new java.awt.Color(227, 235, 238));

        jLabel17.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel17.setText("H extra");

        jLabel18.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel18.setText("Colaborador");

        jLabel19.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel19.setText("H extra noturna");

        jLabel20.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel20.setText("H extra feriado");

        jLabel21.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel21.setText("Total");

        HoraExtra4.setEditable(false);
        HoraExtra4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HoraExtra4ActionPerformed(evt);
            }
        });

        HoraExtraNot4.setEditable(false);
        HoraExtraNot4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HoraExtraNot4ActionPerformed(evt);
            }
        });

        HoraExtraFeriado4.setEditable(false);

        TotalHoraExtra4.setEditable(false);

        Colaborador4.setEditable(false);
        Colaborador4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Colaborador4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PainelColaborador4Layout = new javax.swing.GroupLayout(PainelColaborador4);
        PainelColaborador4.setLayout(PainelColaborador4Layout);
        PainelColaborador4Layout.setHorizontalGroup(
                PainelColaborador4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(PainelColaborador4Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(PainelColaborador4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel18)
                                        .addGroup(PainelColaborador4Layout.createSequentialGroup()
                                                .addGap(6, 6, 6)
                                                .addComponent(Colaborador4, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(23, 23, 23)
                                .addGroup(PainelColaborador4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(PainelColaborador4Layout.createSequentialGroup()
                                                .addGap(19, 19, 19)
                                                .addComponent(HoraExtra4, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(26, 26, 26)
                                                .addComponent(HoraExtraNot4, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelColaborador4Layout.createSequentialGroup()
                                                .addComponent(jLabel17)
                                                .addGap(74, 74, 74)
                                                .addComponent(jLabel19)
                                                .addGap(13, 13, 13)))
                                .addGroup(PainelColaborador4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(PainelColaborador4Layout.createSequentialGroup()
                                                .addGap(38, 38, 38)
                                                .addComponent(jLabel20)
                                                .addGap(78, 78, 78)
                                                .addComponent(jLabel21)
                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(PainelColaborador4Layout.createSequentialGroup()
                                                .addGap(26, 26, 26)
                                                .addComponent(HoraExtraFeriado4, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(28, 28, 28)
                                                .addComponent(TotalHoraExtra4, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 20, Short.MAX_VALUE))))
        );
        PainelColaborador4Layout.setVerticalGroup(
                PainelColaborador4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelColaborador4Layout.createSequentialGroup()
                                .addGroup(PainelColaborador4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(PainelColaborador4Layout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addGroup(PainelColaborador4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel18)
                                                        .addComponent(jLabel19)))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelColaborador4Layout.createSequentialGroup()
                                                .addContainerGap(18, Short.MAX_VALUE)
                                                .addGroup(PainelColaborador4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelColaborador4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                .addComponent(jLabel20)
                                                                .addComponent(jLabel21))
                                                        .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING))))
                                .addGroup(PainelColaborador4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(PainelColaborador4Layout.createSequentialGroup()
                                                .addGap(6, 6, 6)
                                                .addGroup(PainelColaborador4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(HoraExtraFeriado4)
                                                        .addGroup(PainelColaborador4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                .addComponent(HoraExtraNot4, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(HoraExtra4, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addComponent(Colaborador4)))
                                        .addGroup(PainelColaborador4Layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(TotalHoraExtra4, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap())
        );

        PainelColaborador5.setBackground(new java.awt.Color(227, 235, 238));

        jLabel22.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel22.setText("H extra");

        jLabel23.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel23.setText("Colaborador");

        jLabel24.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel24.setText("H extra noturna");

        jLabel25.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel25.setText("H extra feriado");

        jLabel26.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel26.setText("Total");

        HoraExtra5.setEditable(false);
        HoraExtra5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HoraExtra5ActionPerformed(evt);
            }
        });

        HoraExtraNot5.setEditable(false);
        HoraExtraNot5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HoraExtraNot5ActionPerformed(evt);
            }
        });

        HoraExtraFeriado5.setEditable(false);

        TotalHoraExtra5.setEditable(false);

        Colaborador5.setEditable(false);
        Colaborador5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Colaborador5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PainelColaborador5Layout = new javax.swing.GroupLayout(PainelColaborador5);
        PainelColaborador5.setLayout(PainelColaborador5Layout);
        PainelColaborador5Layout.setHorizontalGroup(
                PainelColaborador5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(PainelColaborador5Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(PainelColaborador5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel23)
                                        .addGroup(PainelColaborador5Layout.createSequentialGroup()
                                                .addGap(6, 6, 6)
                                                .addComponent(Colaborador5, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(23, 23, 23)
                                .addGroup(PainelColaborador5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(PainelColaborador5Layout.createSequentialGroup()
                                                .addGap(19, 19, 19)
                                                .addComponent(HoraExtra5, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(26, 26, 26)
                                                .addComponent(HoraExtraNot5, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelColaborador5Layout.createSequentialGroup()
                                                .addComponent(jLabel22)
                                                .addGap(72, 72, 72)
                                                .addComponent(jLabel24)
                                                .addGap(13, 13, 13)))
                                .addGroup(PainelColaborador5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(PainelColaborador5Layout.createSequentialGroup()
                                                .addGap(38, 38, 38)
                                                .addComponent(jLabel25)
                                                .addGap(78, 78, 78)
                                                .addComponent(jLabel26)
                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(PainelColaborador5Layout.createSequentialGroup()
                                                .addGap(26, 26, 26)
                                                .addComponent(HoraExtraFeriado5, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(28, 28, 28)
                                                .addComponent(TotalHoraExtra5, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 20, Short.MAX_VALUE))))
        );
        PainelColaborador5Layout.setVerticalGroup(
                PainelColaborador5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelColaborador5Layout.createSequentialGroup()
                                .addGroup(PainelColaborador5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(PainelColaborador5Layout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addGroup(PainelColaborador5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel23)
                                                        .addComponent(jLabel24)
                                                        .addComponent(jLabel22)))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelColaborador5Layout.createSequentialGroup()
                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(PainelColaborador5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel25)
                                                        .addComponent(jLabel26))))
                                .addGroup(PainelColaborador5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(PainelColaborador5Layout.createSequentialGroup()
                                                .addGap(6, 6, 6)
                                                .addGroup(PainelColaborador5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(HoraExtraFeriado5)
                                                        .addGroup(PainelColaborador5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                .addComponent(HoraExtraNot5, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(HoraExtra5, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addComponent(Colaborador5)))
                                        .addGroup(PainelColaborador5Layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(TotalHoraExtra5, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap())
        );

        PainelBotoesInferiores.setBackground(new java.awt.Color(227, 235, 238));

        BotaoEditar.setBackground(new java.awt.Color(94, 119, 255));
        BotaoEditar.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        BotaoEditar.setText("Editar");
        BotaoEditar.setBorderPainted(false);

        BotaoConfirmar.setBackground(new java.awt.Color(94, 119, 255));
        BotaoConfirmar.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        BotaoConfirmar.setText("Confirmar");
        BotaoConfirmar.setBorderPainted(false);

        BotaoCancelar.setBackground(new java.awt.Color(255, 0, 51));
        BotaoCancelar.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        BotaoCancelar.setText("Cancelar");
        BotaoCancelar.setBorderPainted(false);

        javax.swing.GroupLayout PainelBotoesInferioresLayout = new javax.swing.GroupLayout(PainelBotoesInferiores);
        PainelBotoesInferiores.setLayout(PainelBotoesInferioresLayout);
        PainelBotoesInferioresLayout.setHorizontalGroup(
                PainelBotoesInferioresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(PainelBotoesInferioresLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(BotaoEditar)
                                .addGap(99, 99, 99)
                                .addComponent(BotaoConfirmar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                                .addComponent(BotaoCancelar)
                                .addContainerGap())
        );
        PainelBotoesInferioresLayout.setVerticalGroup(
                PainelBotoesInferioresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(PainelBotoesInferioresLayout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addGroup(PainelBotoesInferioresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(BotaoEditar)
                                        .addComponent(BotaoConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(BotaoCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(PainelColaborador5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(PainelColaborador4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(PainelColaborador3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(PainelColaborador2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                        .addContainerGap()
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addGroup(layout.createSequentialGroup()
                                                                        .addComponent(PainelBotaoVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addGap(272, 272, 272)
                                                                        .addComponent(TituloPagina))
                                                                .addComponent(PainelColaborador1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGroup(layout.createSequentialGroup()
                                                        .addGap(170, 170, 170)
                                                        .addComponent(PainelBotoesInferiores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(PainelBotaoVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(TituloPagina))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(PainelColaborador1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(PainelColaborador2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(PainelColaborador3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(PainelColaborador4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(PainelColaborador5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(PainelBotoesInferiores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
        );

        pack();
    }// </editor-fold>

    private void BotaoVoltarActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void HoraExtra1ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void HoraExtraNot1ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void Colaborador1ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void HoraExtra2ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void HoraExtraNot2ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void Colaborador2ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void HoraExtra3ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void HoraExtraNot3ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void Colaborador3ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void HoraExtra4ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void HoraExtraNot4ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void Colaborador4ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void HoraExtra5ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void HoraExtraNot5ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void Colaborador5ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JButton BotaoCancelar;
    private javax.swing.JButton BotaoConfirmar;
    private javax.swing.JButton BotaoEditar;
    private javax.swing.JButton BotaoVoltar;
    private javax.swing.JTextField Colaborador1;
    private javax.swing.JTextField Colaborador2;
    private javax.swing.JTextField Colaborador3;
    private javax.swing.JTextField Colaborador4;
    private javax.swing.JTextField Colaborador5;
    private javax.swing.JTextField HoraExtra1;
    private javax.swing.JTextField HoraExtra2;
    private javax.swing.JTextField HoraExtra3;
    private javax.swing.JTextField HoraExtra4;
    private javax.swing.JTextField HoraExtra5;
    private javax.swing.JTextField HoraExtraFeriado1;
    private javax.swing.JTextField HoraExtraFeriado2;
    private javax.swing.JTextField HoraExtraFeriado3;
    private javax.swing.JTextField HoraExtraFeriado4;
    private javax.swing.JTextField HoraExtraFeriado5;
    private javax.swing.JTextField HoraExtraNot1;
    private javax.swing.JTextField HoraExtraNot2;
    private javax.swing.JTextField HoraExtraNot3;
    private javax.swing.JTextField HoraExtraNot4;
    private javax.swing.JTextField HoraExtraNot5;
    private javax.swing.JPanel PainelBotaoVoltar;
    private javax.swing.JPanel PainelBotoesInferiores;
    private javax.swing.JPanel PainelColaborador1;
    private javax.swing.JPanel PainelColaborador2;
    private javax.swing.JPanel PainelColaborador3;
    private javax.swing.JPanel PainelColaborador4;
    private javax.swing.JPanel PainelColaborador5;
    private javax.swing.JLabel TituloPagina;
    private javax.swing.JTextField TotalHoraExtra1;
    private javax.swing.JTextField TotalHoraExtra2;
    private javax.swing.JTextField TotalHoraExtra3;
    private javax.swing.JTextField TotalHoraExtra4;
    private javax.swing.JTextField TotalHoraExtra5;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration
}
